[package]
name = "tinykv-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4"
prost = "0.11"
raft-proto = { version = "0.*", default-features = false }
grpcio = { version = "0.*", default-features = false }

[build-dependencies]
prost-build = "0.11"