[package]
name = "tiny-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kv = { workspace = true }
tokio = { version = "1.32.0", features = ["rt", "rt-multi-thread", "macros"] }